# Generated by Django 4.0.6 on 2022-07-20 06:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('published', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1900), django.core.validators.MinValueValidator(2022)])),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('total', models.IntegerField(default=50)),
                ('sold', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('is_staff', models.BooleanField(default=False)),
            ],
        ),
    ]
